INFO     root:HmsManager.py:28 2023-01-20 16:43:13: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-01-20 16:43:13: login HMS success!
INFO     root:HmsManager.py:46 2023-01-20 16:43:13: query gnb info
INFO     root:HmsManager.py:48 2023-01-20 16:43:13: enbId/enbName:4/Automatic-18
INFO     root:CpeManager.py:28 2023-01-20 16:43:13: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:PdcchManager.py:30 2023-01-20 16:43:13: modify PDCCH symbol number,symbol number:1 Symbol
INFO     root:PdcchManager.py:35 2023-01-20 16:43:19: PDCCH symbol number modify success!
INFO     root:CellManager.py:58 2023-01-20 16:43:19: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-01-20 16:43:19: query cell status
INFO     root:CellManager.py:36 2023-01-20 16:43:20: cell status:available
INFO     root:CellManager.py:65 2023-01-20 16:43:20: cell status:available, expect status:available
INFO     root:CpeManager.py:429 2023-01-20 16:43:20: start ue log trace
INFO     root:qutsModel.py:88 printing the chip name of the first device with DIAG_PROT:
INFO     root:qutsModel.py:92 SDX55
INFO     root:qutsModel.py:110 QXDM automation interface successfully launched
INFO     root:qutsModel.py:114 connecting to device with devicehandle=1970324836974592, len=16; protoHandle=1970329131941888, len=16
INFO     root:qutsModel.py:120 QXDM successfully connects to device with deviceHandle=1970324836974592, protHandle=1970329131941888
INFO     root:CpeManager.py:46 2023-01-20 16:43:51: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:120 2023-01-20 16:43:55: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:44:00: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:44:10: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:44:20: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:44:30: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:44:40: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:44:50: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:45:00: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:45:10: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:45:20: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:45:30: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:45:40: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:45:50: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:46:00: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:46:10: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:46:20: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:46:30: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:46:40: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.2.160', '190.3.2.136']
INFO     root:basic.py:30 2023-01-20 16:46:50: wait for 10s......
INFO     root:CpeManager.py:439 2023-01-20 16:47:00: stop ue log trace
INFO     root:qutsModel.py:136 hdf is saved to ['D:\\autotestPro\\AutoTestMain\\qxdmLog\\71bb7cf1-3ece-4375-9d92-44f77062d7e3_50191_Diag_2500-ffff192_168_1_1_0.hdf']
INFO     root:CpeManager.py:451 2023-01-20 16:47:02: PDCCH symbol number params analyze
INFO     root:qCatModel.py:46 Open Ue Log Success
INFO     root:CpeManager.py:457 2023-01-20 16:47:16: check result is:{'duration': True, 'monitoringSymbolsWithinSlot': True}
INFO     root:CpeManager.py:62 2023-01-20 16:47:16: exec detach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=0
INFO     root:cpeModel.py:82 mattch result is:['', 'OK']
INFO     root:test_phy.py:83 2023-01-20 16:47:20: move the log file to backup folder