INFO     root:CpeManager.py:28 2023-01-20 17:00:02: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
WARNING  root:test_cpe.py:67 2023-01-20 17:00:02:run the test <1> times
INFO     root:CpeManager.py:108 2023-01-20 17:00:02: reboot cpe
WARNING  root:test_cpe.py:71 2023-01-20 17:00:07cpe reset success, wait for cpe start
INFO     root:basic.py:30 2023-01-20 17:00:07: wait for 60s......
INFO     root:CpeManager.py:28 2023-01-20 17:01:07: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:120 2023-01-20 17:01:07: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.2.172', '190.3.2.152']
INFO     root:CpeManager.py:73 2023-01-20 17:01:12: exec c5greg command, query cpe's cell info
INFO     root:cpeModel.py:58 AT Command is:at+c5greg=2
INFO     root:cpeModel.py:82 mattch result is:['', 'OK']
INFO     root:cpeModel.py:68 AT Command is:at+c5greg?
INFO     root:cpeModel.py:91 cell info mattch result is:[('2,1,"7D000","1E2130",11,4,"01.01B207"', 'OK')]
INFO     root:CpeManager.py:76 2023-01-20 17:01:20: [192.168.1.1] cpe attach status is: 1
WARNING  root:test_cpe.py:87 2023-01-20 17:01:20: CPE access success rate:1/1